### PR TITLE
Add workflow for linting & testing

### PR DESCRIPTION
**Pull request by adhamarif**
Discussed in Issue #67 and #69.

A github actions is added for:
1. Linting using flake8
2. Unit test using Pytest

### CODE REVIEW

**Comment by adhamarif** [comment]
Removed requirement.txt because we don't have this file in our repository, as we only use the standard libraries in python for this project.

**Review by l4nz8 — CHANGES_REQUESTED** [review]
Looks all good so far, but if I remember correctly you always need a requirement.txt even if there is nothing in there, so I would advise adding it back.

**Comment by adhamarif** [comment]
Update:
1. Created requirement.txt in the repository.
2. Added ` pip install -r requirement.txt` back in the yaml file.

**Review by miriam-agrawala — COMMENTED** [review]
I really like the code - at first I was (also) wondering why the requirements.txt is empty, but when I read the back and forth between you and Vincent in the comment section, it made completely sense!
With the section 
"run: |
    pytest" 
you are calling all the test files (and functions), that have the word "test_" at the beginning, right? So far, I haven't found test functions in the different code folders, so I am wondering, if it makes sense to use pytest in the workflow at this point? (Though I see of course that it will be useful as soon as someone actually uploads test functions)

**Review by miriam-agrawala — APPROVED** [review]
since the code works the same, regardless of the possible changes I was suggesting to discuss in my previous review, I approve this code for merging

**Comment by adhamarif** [comment]
Really good point there! I just put the pytest in advance so that the next time someone make a pull request with their test function, the workflow is already available to test it in github.

**Comment by adhamarif** [comment]
pytest is removed and we have successful workflow for linting. All request have been considered and ready to be merged.

**Pull request merged**
