### PR TITLE
added new file to store picture ASCII graphics

### PR DESCRIPTION
**Pull request by syahidhusein**

### CODE REVIEW

**Comment by syahidhusein** [comment]
As I'm aware, to store the graphics as strings does not work, so I am currently working on storing them as lists and adding a function that would print out elements of the list so it would return the original graphic again.

**Comment by florian-huber** [comment]
ASCII graphics could probably be saved as `.txt` files. 
Also check with @l4nz8 and @till-teb for most recent developments.

**Comment by l4nz8** [comment]
We have two options to read the ASCII images from a .txt. The first possibility would be to save all images together in a .txt file and output them with a paser. The second option would be to save all the images individually as different files which would allow for clarity and better modification of images. I would take the second possibility to save all images individually in an extra folder and call the .txt files depending on the room.

If you need help to access and print the individual files from a folder, I can help you.

**Comment by florian-huber** [comment]
Was continuted in #46 and can be closed.

**Pull request closed without merging**
